<?php include("includes/header.php"); ?>
HELIN <br /> Consortium</h1>

<div id="content">
<br />
        <p>The HELIN Library Consortium is composed of eleven academic libraries and twelve hospital libraries. The academic libraries are represented by  Brown University,  Bryant University, the  Community College of Rhode Island, the  Dominican House of Studies,  Johnson &amp; Wales University,  Providence College,  Rhode Island College,  Roger Williams University,  Salve Regina University,  University of Rhode Island, and  Wheaton College.</p>
        <br />
        <p>The hospital libraries, members of the Association of Rhode Island Health Sciences Libraries (ARIHSL), are represented by Butler Hospital, Kent Hospital, Landmark Medical Center, Miriam Hospital, Memorial Hospital of Rhode Island, Newport Hospital, Rhode Island Hospital, Roger Williams Medical Center, South County Hospital, St. Joseph Health Services of Rhode Island, Women &amp; Infants Hospital, and the Veterans Administration (VA) Medical Center.</p>
        <br />
        <p>HELIN serves a population of over 70,000 students, faculty, and staff at campus locations throughout Rhode Island, Colorado, Florida, Washington, D.C., South Carolina, and Virginia. With the inclusion of Brown into HELIN in May 2002, library patrons have access to approximately 6 million items, including books, periodicals, electronic resources, videos, and audio materials, in a shared library catalog, InRhode. Borrowing library resources is reciprocal among member libraries and is facilitated through online catalog requests. The requested material is delivered using a delivery system maintained through the Rhode Island Office of Library and Information Services.</p>
        <br />
        <p>The HELIN Executive Director, Robert H. Aspri, oversees all HELIN operations, including formulating the budget, and negotiating and overseeing contracts with software, hardware, and electronic resources vendors. HELIN also employs a Systems Librarian, Ruth E. Souto, and a Knowledge Management Librarian, Martha Rice Sanders, who assist the Executive Director in the daily activities of the Consortium.</p>
        <br />
        <p>A Board of Directors, consisting of the library directors from each of the ten full member libraries and the HELIN Executive Director, governs the HELIN Library Consortium. The Board of Directors also includes four elected representatives, who, along with the Executive Director, and the Past President of the Board comprise the HELIN Executive Board. The President of the HELIN Executive Board is Mary Moroney, Director of Library Services at Bryant University; Vice President is D. Russell Bailey, Directory of Library Services at Providence College; Treasurer is Terry Metz, Vice President for Library and Information Services at Wheaton College ; and Secretary is David Maslyn, Dean of Libraries at the University of Rhode Island.</p>
        <br />
        <p>The HELIN Consortium was incorporated in 2005 and is bound by an &quot;Agreement for Integrated Library and Information Services&quot; signed by all parties. HELIN has a set of Bylaws that are based upon the &quot;Agreement for Integrated Library and Information Services,&quot; and the bylaws are an extension of that document. In order to support the intellectual freedom of the members of its constituent libraries the HELIN Consortium maintains a HELIN Policy on Confidentiality of Records. HELIN also has standing committees, composed of library staff from each of the member libraries:  Access Services Committee, Acquisitions Committee, Cataloging Committee, Collection Development Committee, Government Documents Committee, Reference Committee, and Serials Committee.</p>
        <br />
        <p>The HELIN Consortium was formed in 1984, when the libraries of the three state institutions of higher education, the University of Rhode Island, Rhode Island College, and the Community College of Rhode Island, began a cooperative agreement to share an automated circulation system. In time, the automated circulation system was replaced by a multi-functional automated library system purchased from Innovative Interfaces, Inc. In 1990, Roger Williams University joined HELIN, followed by Providence College in 1992, Johnson &amp; Wales University in 1997, Salve Regina University in 1999, Bryant College in 2001, Brown University in 2002, both the Dominican House of Studies and the fifteen health sciences libraries in 2003, and Wheaton College in 2005. The Rhode Island State Law Library, also known as the Supreme Court Library will become HELIN's newest member when they offically join in July 2009.</p>
<br />
</div>
<?php include("includes/footer.php"); ?>